### ISSUE TITLE
Enabling HTTPS in learning locker

### ISSUE THREAD

**Issue by RS1603** [LearningLocker/learninglocker#1068]
You need to replace the parts of this template where you see {{some text}}.

Learning Locker : v2.0.1
Mongo DB : 3.4.9
Redis: 2.8.11

Steps to reproduce the bug

{{step 1}}
{{step 2}}
Expected behaviour
Enabling https

Actual behaviour
Not able to locate the Index.php file

Additional information
OS Version
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"

Problem Statement: Enable Https in the URL request

Until Now: Certificates installed on the Wildfly server
                  Followed this link to enable https : https://nithinkk.wordpress.com/2017/03/16/learning-
                  locker/
                  As suggested in the site : enable https in Index.php file
	          Not able to locate Index.php file in the current installation directory of Learning Locker V2
		   
	     Went through the feature of Learning Locker:
	     This link shows that SSL is available with enterprise edition : https://www.ht2labs.com/learning-
             locker/enterprise-lrs-features/#.WjgX-lWnGpo : 
		   
Questions to Learning locker:

1. Since the Version 2.0, they have rebuilt the core codebase to deprecate PHP in favour of NodeJS, and bring the Open Source Edition in line with Learning Locker Enterprise. 
Is the folder structure and the file to enable https has been changed? If yes, can you please help us with the file.
2. Is this a feature specific to enterprise edition

**Comment by ht2** [comment]
HTTPS is something you can either configure at the load balancer or server level, this is not a Learning Locker specific feature.

https://aws.amazon.com/blogs/aws/new-aws-certificate-manager-deploy-ssltls-based-apps-on-aws/
http://nginx.org/en/docs/http/configuring_https_servers.html

**Comment by RS1603** [comment]
Hi James,

I have installed the certificates, whenever I send the learning locker request with https. It doesn't work.
Any suggestion will help.

Thanks and Regards,
Rajshree

**Comment by ht2** [comment]
Hi Raj, Sorry but we don't offer support for server setup. Please contact your administrator.

**Comment by adrianvaneeden** [comment]
Hi, I know this is an old topic but it was one of the few I found on the subject and thought this might help a few people.

I was running a custom installation of Learning Locker v2 and could _not_ get SSL loaded, which was a problem because my front-end LMS was encrypted and any calls were getting _unauthorised_ failures.

I'd originally loaded the dev machine bare-metal on AWS EC2 but then I found the ht2labs AMI image so decided to test with this instead.  It also installed on port 80 by default, and interestingly, when I compared their image to the one I'd done, there was very little difference.  So who know.

Working from the AMI Marketplace image though...

They current image runs on Ubuntu 16.04.  I avoided doing any updates or upgrades.  

To be safe, I backed up everything I could - /var/nginx/nginx.conf and /var/nginx/conf.d folder in particular.

I used LetsEncrypt because, well, free trusted certificates!  Follow their instructions to add a certificate using certbot from [https://certbot.eff.org/](https://certbot.eff.org/) .  There are a few funnies.  I think because of old versions of software.  this is what happened to me, hope these help:

When I tried to install the certbot repo (`sudo add-apt-repository ppa:certbot/certbot`) I got pages of errors with python and file not found warnings.  I had to re-install the ca certs as per [this page](https://stackoverflow.com/questions/43308552/filenotfounderror-add-apt-repository-ppacertbot-certbot/44204636#44204636).  After that the add repo worked.

When that was sorted, of course you update -   `sudo apt update`,  and follow the rest of the steps listed on the certbot site (not reproduced here in case they have change when this is read).

Then when I ran the certbot installation (`sudo certbot --nginx`) I got the following error:  _Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA_.  

Again, I think because time moves on, the TLS standards have been upgraded and for some reason the version of certbot that was on the machine was old (no idea why).   I installed a second time (`sudo apt install python-certbot-nginx`) and it upgraded.  I have absolutely no idea why the version mismatch when I installed everything on the same day, I might have made a mistake somewhere early in the process, but I have crashed too many servers with certs to have the courage to try reproduce, sorry.

When updated, the certbot process works - put in your url, follow the instructions, and last step, make sure to ask it to redirect port 80 at the end.  

And all good.  Restart Nginx just in case (`sudo systemctl restart nginx` if you're not in production).

tl?dr
Because h2tlabs run on Node and Express I was a bit worried that the http protocol was hard-coded into their JavaScript.  But their image and their custom installation example put an Nginx web server in front of the Express listener, and their sample Nginx conf file includes proxy forwarding, so all you really need to do is change NginX and block direct access to the Express ports and you should be good.

In theory with the above config, you could still access the Learning Locker APIs directly with the ports configured in their .env files (e.g. 3000 for the UI) but this would be unencrypted, and considering the sensitivity of this type of data, not very responsible.  I blocked access to these ports (3000, 8080, 8081) with Ubuntu iptables (or probably easier, ufw) so the only entry point is on the 443 port.  

I had a hard time getting my LMS (LearnDash) talking to the LRS originally, but this way worked perfectly.  If you're really techncial, PostMan is a nice way of testing the XAPI and API endpoints.  It's so satisfying to see the data come back like that.

The other thing to remember if you are like me and changed to https halfway through the process, is that you need to check that all your endpoints are now `https` not `http`.  I use Grassblade XAPI companion to upload XAPI content, and it doesn't regenerate the URI's automatically, so I had to go through each post manually.

**Comment by jonathanvdmerwe** [comment]
apt-get install --reinstall ca-certificates
update-ca-certificates

Then try "add-apt-repository ppa:certbot/certbot"

This should work out the issues

**Comment by TheJoshuaEvans** [comment]
@adrianvaneeden Thanks! Your advice is super helpful. These are the exact commands I used to get ssl up and running on the "Learning Locker 4.10.0 from HT2 Labs" AMI :
```
sudo apt-get install software-properties-common
sudo add-apt-repository universe
sudo apt-get install --reinstall ca-certificates
sudo update-ca-certificates
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install certbot python-certbot-nginx
sudo certbot --nginx

```
(It probably wouldn't hurt to do a `sudo apt upgrade` as well, but it's not required to get ssl/tls up and running)

**Comment by raisharan7** [comment]
@TheJoshuaEvans @jonathanvdmerwe Hello. It asks for the Domain name at the last step, should i put the public DNS provided by AWS or make another Domain and have my public IP in it and then use that domain in this step?
Thanks in advance

**Comment by TheJoshuaEvans** [comment]
@raisharan7 I believe that certbot actually blacklists the public DNS provided by AWS (it will refuse to generate certs for these default addresses), you will need to make another domain 👍

**Comment by raisharan7** [comment]
@TheJoshuaEvans I created a domain and added the certs and the commands worked fine for me.
Thanks a lot

**Comment by adrianvaneeden** [comment]
Glad you came right 👍
