### ISSUE TITLE
Statement causes /data/xAPI endpoint to hang and eventually crash

### ISSUE THREAD

**Issue by ccopland94** [LearningLocker/learninglocker#1103]
**Version**
Learning Locker version 2.1.1

**Steps to reproduce the bug**
POST the following to the /data/xAPI/statements endpoint:
`[{"id": "2580855f-ea87-11e7-954d-9cb6d063d616", "actor": {"name": "D791D", "account": {"name": "D791D", "homePage": "https://example.com"}}, "verb": {"id": "http://adlnet.gov/expapi/verbs/answered", "display": {"en-US": "answered"}}, "object": {"id": "https://example.com/step/%28EQN%20%28%3D%20%7CYc_Fw_DUMPSTER_EARTH_1_15%7C%20%28%2A%20%7CFw_DUMPSTER_EARTH_1%7C%20%28SIN%20%28-%20%28DNUM%20270%20%7Cdeg%7C%29%20%28DNUM%2015%20%7Cdeg%7C%29%29%29%29%29%29", "objectType": "Activity"}, "context": {"contextActivities": {"parent": {"id": "https://example.com/problem/S2B", "objectType": "Activity"}, "grouping": {"id": "https://example.com/problem/S2B", "objectType": "Activity"}}}, "result": {"duration": "PT10.0S", "success": false, "response": "-F3y_y = m*g"}, "timestamp": "2008-09-30T03:39:43+00:00", "version": "1.0.3"}]`

**Expected behaviour**
Statement should post to the LRS. All of the credentials and headers are correct, as other statements will make it in.

**Actual behaviour**
The endpoint hangs and eventually times out. It appears to be an issue with the object id URL. When I change that URL to something else without any encoded characters, the statement goes through (even if the URL is longer than that one). The /data/xAPI service then requires a restart.

**Additional information**
OS: Ubuntu 16.04/Apache

**Comment by fugu13** [comment]
Hi @ccopland94, this is almost certainly related to an issue identified and fixed a few weeks ago with the IRI regex: https://github.com/LearningLocker/xapi-validation/commit/d504e0e27e6471f6c83d2a09c31bf0f9751557b8#diff-02e39d607a4ffca50fdb961298551a50

Not sure what release that's in, but I'm sure someone from the Learning Locker team will know.

The regex since then has been updated to be much more permissive, though overly so (lots of illegal IRIs will now be allowed). Taking a peek at the regexes that were causing the problem, I'd normally solve it in a straightforward way with a few atomic grouping or possessive quantifiers, but javascript doesn't support those directly; they can be emulated with only slightly more complexity in the regex, though. It could also be solved by modifying the the regex to match boundaries more explicitly, which would also prevent backtracking. I'd recommend the team look into that pretty quickly, before people's databases become full of not-quite-legal IRIs.

**Comment by ccopland94** [comment]
@fugu13 Thanks - it does look like this is related to that issue. I will try to install that version and see if that fixes the issue.

**Comment by ht2** [comment]
Thanks for the insight @fugu13, yes we had to backtrack quite aggressively due to some limitations in the V8 regex that allowed for circular routes in the regex patterns! We're aware of the limitation there and we're looking into solutions. In the meantime hopefully you are seeing your issue solved @ccopland94 and I'll close this off.
