### ISSUE TITLE
Object ID not display correctly in statements

### ISSUE THREAD

**Issue by roblowney** [LearningLocker/learninglocker#1113]
You need to replace the parts of this template where you see {{some text}}.

**Version**
v2.0.6

**Steps to reproduce the bug**
1. Created an Articulate Presenter course and exported to HTML5 output with flash fallback
2. Configured an instance of Tin Can Launch Link in Moodle to launch the Articulate course
3. Went through course
4. Learning Locker received all required statements (e.g. launched, experienced, completed)

**Expected behaviour**
When expanding a statement to look at more detail, the object ID should be displayed in the format "http://activityid/objectid"

**Actual behaviour**
When expanding a statement to look at more detail, the object ID just displays as "http://"

**Additional information**
OS: Windows 10
Browser: Chrome Version 63.0.3239.132
Moodle version: 3.1

**Comment by ht2** [comment]
Hi @roblowney - firstly I'd ask if you could try this on the latest version of Learning Locker as 2.0.6 is quite out of date. Secondly, this sounds like Articulate isn't sending the right data - the "statement.object.id" is stored "as sent" and isn't manipulated as far as I know. If you can intercept the Presenter xAPI POST and validate that the statement being sent _definitely_ sends the full activity ID then we can look into this, but to me this sounds like a client (Articulate) issue rather than a Learning Locker one.

**Comment by hallshouse** [comment]
I'll chime in to confirm it is a Articulate issue. Not many LMS/LRS systems are supporting Presenter, Studio, or Rise because these products are deficient. those LMS systems supporting Rise had to create code exceptions to do it.

I only just got an email from Articulate Engineering saying they have fixed Rise to be xAPI compliant (by the spec), but have no time to test myself.

**Comment by ht2** [comment]
Thanks @hallshouse - I'm going to tentatively close this issue unless @roblowney can action the requests I outlined above and replicate it.
