### ISSUE TITLE
Insert speed

### ISSUE THREAD

**Issue by doender** [LearningLocker/learninglocker#1114]
**Version**
2.0.7

We are stress testing our LRS on Debian Wheezy, 2xCPU, 4GB RAM and when constantly inserting statements we see that only around 1k statements per minute can be inserted (with a very high load, making the LRS unresponsive). Can this be improved? . 

I'm not sure, but it looks like the LRS is checking for statement uuid collisions before inserting. Does this cause it to be slower and could this be disabled? 
BTW: we don't set statement ids ourselves when sending the statements. Does it help to set them?

**Comment by ht2** [comment]
Have you added the required indexes? How many statements do you currently have in your database? If you have run the migrations then these will be added for you (http://docs.learninglocker.net/guides-cli/#migratemongo) but otherwise you can [manually add them](http://docs.learninglocker.net/guides-indexing/).

Obviously things depend greatly on your Mongo setup. Do you have that on a seperate server? If not, you should consider splitting your application infratructure from your database as Mongo is very memory heavy.

Are you sending you statements in batches? Typically we see inserts of 100 statements (in a single request) take ~200ms on our setups. Batches of 1000 can be inserted in sub 1 second times.

I'd also recommend you upgrade your instance, we've had a large number of updates to the xAPI Service since 2.0.7 that will ensure you are running the best version of the codebase.
