### ISSUE TITLE
Invalid xAPI statement: context.platform and StatementRef

### ISSUE THREAD

**Issue by doender** [LearningLocker/learninglocker#1148]
**Version**
2.3.0

We are getting an error when trying to insert a statement with objectType "StatementRef" and "context.platform" is set. In the LL tests we found out that this is invalid: https://github.com/LearningLocker/xapi-validation/blob/e86a4de8fe4183659f0eb1d071a494777bd246b9/src/tests/helpers/statementRules.ts#L17

Could you please explain why setting a platform is invalid in this case?

**Comment by ht2** [comment]
Hi @doender,

As per the specification, platform can only be set if the statement's object is an Activity. You are setting a StatementRef

https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#requirements-10

James

**Comment by ht2** [comment]
Presumably this is because if you are referencing the statement, then the platform can only make sense in the context of the statement being referenced. If you could set a platform when setting a StatementRef then you could effectively have a mismatch on platform between the referencing statement and the referenced statement.
