### ISSUE TITLE
Nagendra cloud engineer

### ISSUE THREAD

**Issue by vasudeva1234** [LearningLocker/learninglocker#1226]
Hi,
i am getting error at login phase....please find out the error given below

There was an error communicating with the login server.

Thanks in advance,
Nagendra.J

**Comment by vasudeva1234** [comment]
logo
MAKING LEARNING MEASURABLE
Welcome
E-Mail
ht2testadmin@ht2labs.com
Password
••••••••••••
Error:There was an error communicating with the login server.
 Login
 Reset password
© 2018 HT2 Labs
v2.4.0

**Comment by ht2** [comment]
Please submit using our issue template

You need to replace the parts of this template where you see {{some text}}.

**Version**
{{branch}} at {{commit}} on {{version - found in your copy of the VERSION file}} 

**Steps to reproduce the bug**
1. {{step 1}}
2. {{step 2}}

**Expected behaviour**
{{feature}} should be {{expectedResult}} because {{reason}}.

**Actual behaviour**
{{feature}} is {{actualResult}}.

**Additional information**
OS: {{operatingSystem}}
Browser: {{browser}} version 1.0.1
{{additionalInfo}}
