### ISSUE TITLE
Contribute on French translation

### ISSUE THREAD

**Issue by etiennej70** [LearningLocker/learninglocker#1267]
Hello,
I would like to contribute to learning locker translation by adding French support. How can we make it possible ?
Thks

**Comment by ryansmith94** [comment]
To be honest @etiennej70 that's going to be really difficult right now since a lot of the displayed text is hardcoded. The best solution to this problem right now is just to set your Browser to "always translate" the page from English to French. Whilst this probably sounds like a terrible solution, it's probably the most maintainable solution going forward because we don't have anyone that speaks French on the team in order to keep the translations up to date as we quickly and continuously develop Learning Locker.

**Comment by etiennej70** [comment]
Hello,

What about remove theses hardcoded labels during your next developments and move them to a translation process (by json or other files) and give a way to the community to contribute ? I guess a lot of users should contribute :) And give you the english as fallback solution at anytime ?
It's a huge issue for the expansion of your LRS solution worldwild I think ;)

BR,

**Comment by ryansmith94** [comment]
In previous internal conversations about translations we have discussed having a series of translation functions replace the hard-coded labels with a fallback to English. We don't think this is a huge issue because there are many other things that people ask for more frequently and from our experience with version 1 translations did very little to expand the use of Learning Locker worldwide.

Like I said before, the best solution to this problem right now is just to set your Browser to "always translate" the page from English to French.
