### ISSUE TITLE
Redis authentication

### ISSUE THREAD

**Issue by mvalenzisiAK** [LearningLocker/learninglocker#1413]
The XAPI component uses the variable `REDIS_URL` where it is possible to specify (from the documentation):
> The full URL of the Redis instance including port, database number and authentication if required

The same does not apply to the Learning Locker Application, that uses the variables `REDIS_HOST`, `REDIS_PORT`, `REDIS_DB` and `REDIS_PREFIX`.

It would be helpful to have the same Redis configuration that is used for the XAPI also in the Learning Locker Application.

As an alternative, two new variable could be added to the Learning Locker Application, something like `REDIS_ACCESS_KEY` and `REDIS_USE_SSL`

**Comment by WillSkates** [comment]
Try this on a staging environment and see if it works for you:

```diff
diff --git a/lib/connections/redis.js b/lib/connections/redis.js
index 66015a4e..2ccb2ec9 100644
--- a/lib/connections/redis.js
+++ b/lib/connections/redis.js
@@ -19,6 +19,9 @@ export const getOptions = () => {
       return { db, password, name, sentinels };
     }
     default: case 'redis': {
+         if (process.env.REDIS_URL !== undefined) {
+           return process.env.REDIS_URL;
+         }
       const db = defaultTo(Number(process.env.REDIS_DB), 0);
       const password = process.env.REDIS_PASSWORD;
       const host = process.env.REDIS_HOST;
```

**Comment by caperneoignis** [comment]
None of the variables match between the two services. I believe this was done because LL doesn't want variables in the xapi, backend, service being used in the frontend service. Not everyone will want the same redis server being used by both services, or MongoDB. that's why the Mongo connection string is also different. The services are built to be separate but can run on the same server, either at the same time or by themselves. 

But I might be wrong on that.

**Comment by mvalenzisiAK** [comment]
@caperneoignis 
What you say makes sense. The goal of my request is to be able to use an access key with ssl for the Redis connection in the webapi configuration, I don't mind if the variable names are different.

**Comment by caperneoignis** [comment]
@mvalenzisiAK I got yea, the way I did it, was through stunnel. So the access key goes into the connection string, and then I used a different port (or the same port if you have the locally installed redis server turned off) and had stunnel do the secure connection to the redis server.

**Comment by caperneoignis** [comment]
@mvalenzisiAK Actually, I see redis is just now supporting TLS [REDIS Issue](https://github.com/antirez/redis/pull/4855) Sentinel shouldn't be too far behind if not already done. I'll ask @ryansmith94 if and when there is a plan to update redis with the newest version that allows TLS and when they plan to add the ability to use TLS to the APP. Not sure how many places have to be updated to allow for TLS connections but I can't see it being too hard. 

If you want to add the code, I'm sure they wouldn't say no.

**Comment by mvalenzisiAK** [comment]
@caperneoignis adding the code is a bit far beyond my capabilities but I will take your suggestion and try stunnel for the time being!

**Comment by ryansmith94** [comment]
Hey thanks both, I think this is quite important, I've made a ticket for it, might be able to get someone to investigate in the next few days.

https://learningpool.atlassian.net/browse/LL-137

**Comment by ryansmith94** [comment]
Some progress being made here https://github.com/LearningLocker/learninglocker/pull/1423

**Comment by WillSkates** [comment]
@ryansmith94 Does the logger component have some magic where it escapes or replaces environment values in it's output? In which case you probably don't want to log sensitive information to the user. see #1423.

This might be out of scope here but is there any desire to support container systems that mount secrets using volumes? In that case there is usually a corresponding "*_FILE" environment variable that contains a path to a file that contains the value. The [MySQL](https://hub.docker.com/_/mysql#docker-secrets) container image does this.

**Comment by ryansmith94** [comment]
@WillSkates no it doesn't escape or replace environment variables. In some cases we want them logged out. Typically when a user has access to the logs, the user also has access to the environment variables too. Do you have an example of where this isn't the case?

**Comment by WillSkates** [comment]
@ryansmith94 that shouldn't be typical. For example you can have access to an applications stderr/stdout output without having access to the process environment at all. Particularly if you pipe it into a file or you use a service to do your logging.

Can you provide an example where you would want to output them? I'm not sure that credentials being incorrect _**should**_ ever be a problem after you deploy for the first time.

I'm also only talking about the username & password components. The patch I submitted does log the hostname, port etc.

**Comment by ryansmith94** [comment]
Perhaps it shouldn't be typical and will become less typical, but right now for the majority of people installing Learning Locker it is typical and that's even true here, only our system admins have access to the logs and the process environment.

Probably wouldn't want to output them in production, but certainly in development we sometimes want to output them for debugging purposes to make sure the right values are being used in certain parts of the code.

**Comment by WillSkates** [comment]
Do you need to double up on the information in development? You should have access to the process environment.

**Comment by ryansmith94** [comment]
It's for ensuring the values are ingested correctly by the code, so the process environment isn't enough.

**Comment by WillSkates** [comment]
That would give you access to the environment variables and the output so you should have what you need. Apologies as we've spoken for a while about this now I think there's just something obvious that I'm missing.

It sounds like you need to check for these at startup:
1. Have the value been set? - If not say so...
2. Are the values valid? - Covered by exception output.
3. Do we need to log the sensitive information out? If so... print it. (Default off instead of default on.)

If that's correct [does this](https://github.com/LearningLocker/learninglocker/compare/LL-137-add-support-for-Redis-authentication...WillSkates:LL-137-add-support-for-Redis-authentication) suit you?

Cheers,
Will

P.S. Apologies if the above has errors in it. I don't currently have the time to set up a working environment for it.

**Comment by ryansmith94** [comment]
That's okay, I appreciate that it's important to you. Unfortunately due our current ad-hoc usage of environment variables we can't really just check them on startup. In the future I hope we will have a single file in the codebase that ingests and validates the environment variables so that we can just check them on startup. With that in place we can ensure that process.env isn't used outside of that one file.

**Comment by WillSkates** [comment]
Ah OK I did a quick search in the codebase to see what you mean. The best you can do right now is initialize the objects that you need statically and then only invoke their creation once.

[See here](https://github.com/LearningLocker/learninglocker/compare/LL-137-add-support-for-Redis-authentication...WillSkates:LL-137-add-support-for-Redis-authentication#diff-3f902982bbe83395290492bb3a478687R114)

**Comment by ryansmith94** [comment]
Yeah that would be quite a significant change in a bunch of areas. I think for now we'll try to make sure sensitive info isn't logged and we'll look at this again later.

**Comment by ryansmith94** [comment]
Hey @mvalenzisiAK, support for the `REDIS_URL` has been added in [v4.6.0](https://github.com/LearningLocker/learninglocker/releases). I hope that solves your issue, if not please reopen this.

**Comment by mvalenzisiAK** [comment]
@ryansmith94 glad to hear!
Thank you all!
