### ISSUE TITLE
Creating Redis client redis://127.0.0.1:6379/0

### ISSUE THREAD

**Issue by fishfree** [LearningLocker/learninglocker#1449]
I followed this instruction to install the learninglocker 2. When I run: pm2 log. It showed error:
`2|Worker   | 2019-09-07 06:10:53:288 - error: Creating Redis client redis://127.0.0.1:6379/0`
I then changed to "REDIS_URL=redis://127.0.0.1:6379/1" in the .env file. But it still showed error:
`2|Worker   | 2019-09-07 06:21:32:265 - error: Creating Redis client redis://127.0.0.1:6379/1`

I'm sure my redis-server is running. Because there is annother application is using redis as cache in my server.

**Comment by bitcrush** [comment]
I ran into this as well. I believe this is a bug in [redis.js](https://github.com/LearningLocker/learninglocker/blob/46213c6cadd125da667421f0a88207c7aeda8c5b/lib/connections/redis.js#L41), where `error()` instead of `info()` is used in the `catch` block:
```javascript
logger.error('Creating Redis client', options);
```
should actually say:
```javascript
logger.info('Creating Redis client', options);
```
So you can safely ignore the error message.

**Comment by etcsayeghr** [comment]
Is there a fix to this? It fills up our logger to the point where it eventually brings down the server.

**Comment by ryansmith94** [comment]
@etcsayeghr how many days worth of logs are you keeping? Ideally these need clearing down periodically, this is what we do on our servers. If this is an issue with the dependency then we need to update the dependency and hope the log has been removed.
