### ISSUE TITLE
Production LL still tries to send pretend emails

### ISSUE THREAD

**Issue by davidpesce** [LearningLocker/learninglocker#615]
**Version**
1.3.10

**Steps to reproduce the bug**
Fresh install of LL 1.3.10
Add mail settings to mail.php
Verify 'pretend' is set to false

**Expected behaviour**
Register new user/verify email address should send an actual email.

**Actual behaviour**
Checking laravel.log shows that a pretend email was "sent"

**Server information**
CentOS 7 (remote server, not local)
MongoDB

**Client information**
OS: Windows 8.1
Browser: Chrome (latest)

**Comment by ryansmith94** [comment]
Hi David, thanks for your issue. Please can you check that the correct configuration is being used because we recently started defaulting to local.

The quote below is from the [1.3.10 release notes](https://github.com/LearningLocker/learninglocker/releases/tag/v1.3.10).
> If you're upgrading with Github you may get some merge conflicts on line 33 of the "bootstrap/start.php" file. Replace gethostname() on line 33 with your own hostname, or replace local on line 33 with your own environment name (such as "production" which was the previous default). This was changed in #598 to improve startup issues.

**Comment by davidpesce** [comment]
Oddly, yeah it did fix it. Unfortunately, it removed all my LRS's and statements. 

Is there a reason it's defaulting to local? Seems odd unless LL is being targeted at testing only.

**Comment by ryansmith94** [comment]
Yeah you'll also need to change the other configuration files inside "app/config/local" like "database.php".

Yeah there are two reasons. Firstly, we want to remove steps from installation to make it easier for beginners. Secondly, we have to use the append_config method in order for one of the service providers to work (see snippet below), so we can't really default to the global config when it actually won't work correctly in some cases.

```php
'providers' => append_config(array(
  'Jenssegers\Mongodb\Auth\ReminderServiceProvider'
))
```

Sorry if this has been a inconvenience for you. We had a lot of issues caused by the defaulting to production instead of local last week so this was our solution.
