### ISSUE TITLE
Upgrading statements from many versions ago

### ISSUE THREAD

**Issue by ppounder** [LearningLocker/learninglocker#751]
Hi all,

I installed learning locker over a year ago, and due to workloads have not had chance to keep it up to date. Unfortunately I can't tell what version it is. I installed around Aug 2014. I would like to try and run the latest version, and I'm trying to understand how I go about upgrading my statements that I currently have (over 60,000). into the newer format. I have the new version of LL running fine and my current custom built LMS is firing into it fine.

I've tried running ````php artisan migrate --env=local```` on a few statements, but that didn't work.

My old statements do not have the following:
````
lrs_id
client_id
active
voided
statement.version
````
My current ````lrs._id```` is just a string, not an Objectid(;;) either.

Have you any suggestions on how I go about upgrading from such an older version?

Cheers
Paul

**Comment by pondermatic** [comment]
I recently upgraded several installations from [v1.1.2](https://github.com/LearningLocker/learninglocker/releases/tag/v1.1.2), released Oct. 23, 2014, to [v1.11.0](https://github.com/LearningLocker/learninglocker/releases/tag/v1.11.0) and had to first upgrade to [v1.3.9](https://github.com/LearningLocker/learninglocker/releases/tag/v1.3.9) because that's the last version that `php artisan ll:migrate-statements` works.

Here are my upgrade notes:
```Shell
set LARAVEL_ENV=local
git checkout -f v1.3.9
composer install
# "bower ECONFLICT Unable to find suitable version for underscore"
# This is OK. bower is last step in composer.json post-install-cmd

# edit app/config/local/app.php and app/config/local/database.php

php artisan migrate
php artisan ll:migrate-statements

git checkout -f v1.11.0
composer install
# sh refresh.sh will throw errors on windows. Never mind them.

# edit app/config/local/app.php and app/config/local/database.php

php artisan migrate --env=local
```
`lrs_id` property added by `app/database/migrations/2015_08_12_150203_ConsistentForeignKeyNames.php`.

There does not appear to be a migration for adding the `client_id` property to the statements collection. Hmm.

`active` and `voided` properties are added by `app/commands/StatementMigrateCommand.php` (`ll:migrate-statements`).

My old statements already had `statement.version`.

**Comment by ppounder** [comment]
Thanks @pondermatic Looks like I'll have to do something similar, but look into a version or two before to see if I'll need to run migrate on them.

**Comment by ppounder** [comment]
For anyone else interested, I've managed to do this.

I've installed all the LL's that required artisan migrations, and ran the artisan migrate scripts in order of release. Bit of a bind, but that's my fault for not keeping it up to date.

All sorted and working on the latest version.

Great work folks.
