### ISSUE TITLE
artisan migrate failing in v.1.12 with large collection

### ISSUE THREAD

**Issue by scmc** [LearningLocker/learninglocker#791]
running 

 php artisan migrate --env=production 

[MongoCursorTimeoutException]                                                                      
  lrsdbxxx01.ctlt.ubc.ca:27017: Read timed out after reading 0 bytes, waited for 30.000000 seconds  

Migration scripts really need to set  'socketTimeoutMS' => -1 
I suggested on this pull.
https://github.com/scmc/learninglocker/commit/0703c7606ebf06838675804fe37f0cea23cb637b

**Comment by ht2** [comment]
Hi @scmc, what version are you migrating from?

**Comment by ht2** [comment]
Also, regarding the [commit/PR](https://github.com/scmc/learninglocker/commit/0703c7606ebf06838675804fe37f0cea23cb637b) you made, I don't believe you ever submitted it the learninglocker repo, rather than a PR to your only fork's version of develop, hence it never got seen.

If you want to submit the PR to `learninglocker/learninglocker/develop` then I would be happy to merge that in assuming all tests pass.

**Comment by ht2** [comment]
Actually, even better; submit to [`issue/timeouts`](https://github.com/LearningLocker/learninglocker/tree/issue/timeouts) and I will go back through the other migrations and ensure the relevant flag is set for other places we are doing similar large updates.

**Comment by ryansmith94** [comment]
Archiving due to inactivity.
