### ISSUE TITLE
Poor LRS performance 

### ISSUE THREAD

**Issue by lanauri** [LearningLocker/learninglocker#836]
Hello,

We configured an LRS to store Moodle records but we do not get the performance we need. We need to store 1000 logs per minute and by now we only can store 300 per minute.

For this reason we tried to change the cache configuration to memcached supposing that that would improve the LRS performance .
- We installed memcached and php5-memcached components.
- We changed the 'driver' => 'memcached'  in the "app/config/cache.php " file
- and we restarted the sevice but memcached is not used.

Could you help us to configure LRS to use memcached?

Is this the best option to improve the performance of the LRS ?
Or are there other changes to do to improve LRS performance?
Can we find any documentation about that anywhere?

Thank you,
noèlia
 

**Version**
1.13.1

**Steps to reproduce the bug**
1. Change  'driver' => 'memcached' in the "app/config/cache.php" file

**Expected behaviour**
memcached should be used because the change in the configuration described in step 1

**Actual behaviour**
memcaches is not used

**Additional information**
OS: Ubuntu 14.04 LTS
Browser: Firefox

**Comment by ht2** [comment]
Sorry @lanauri, not entirely sure why you are trying to change the cache driver? Can you explain your thinking - the cache isn't used in the code base, so changing the driver would have no effect.

It sounds like you need to better tune or scale up your architecture (e.g. Nginx and php-fpm configurations, load balanced machines, horizontal vs vertical etc).

As this is not an application issue, but rather an architecture one I am going to close this issue. I would suggest you please take this kind of query to the Gitter channel if you would like to discuss options with the community. Otherwise you should look into reaching out to other support channels such as enterprise hosting and support.
