### ISSUE TITLE
statement "stored" value is not a valid timestamp for filter

### ISSUE THREAD

**Issue by alexeypolyakov** [LearningLocker/learninglocker#844]
You need to replace the parts of this template where you see {{some text}}.

**Version**
1.13.3

**Steps to reproduce the bug**
1. Put a statement into lrs then read it back and get stored value: String stored = client.get(result).getStored();
2. Get statements from LRS using "since" filter: StatementResult statements = client.filterBySince(stored).ascending(true).getStatements();
3. Get error 400 with message:
 message:["`2016-07-12T15:33:18.656000 00:00` should be a valid `Locker\\XApi\\Timestamp

**Expected behaviour**
Server must return statements stored after first statement if any.
"stored" has the same formatting requirements as "timestamp" (MUST be formatted according to ISO 8601)
see https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#stored

**Actual behaviour**
Error 400 with message:
 message:["`2016-07-12T15:33:18.656000 00:00` should be a valid `Locker\\XApi\\Timestamp

**Additional information**
OS: Linux
Browser: Chrome

**Comment by ht2** [comment]
The statement returned should always have a valid ISO timestamp. Can I assume you are using a library to pull out the stored timestamp (client.filterBySince(stored).ascending(true).getStatements();)? You need to check the actual response from the locker, rather than relying on the value the library is giving you.

If you can reproduce this problem directly from the locker using a tool such as Postman we would be able to look into this, but we cannot replicate this. As such, I would double check the library.

**Comment by alexeypolyakov** [comment]
When I browse statements on server I see:
    "timestamp": "2016-07-12T15:43:11.777Z",
    "stored": "2016-07-12T15:47:01.828000+00:00"
It uses different formats

**Comment by ht2** [comment]
They are both valid valid ISO8601 formats. In your first example it is missing the `+`, hence it is invalid.

**Comment by alexeypolyakov** [comment]
Thanks.
The problem was that library is not properly encoding the value when constructing GET-request.

**Comment by alexeypolyakov** [comment]
The issue is that library is not properly encoding url parameters when constructing GET-request.

**Comment by ht2** [comment]
Right, makes sense
