### ISSUE TITLE
Learning Locker navigations not working on IIS

### ISSUE THREAD

**Issue by lagost** [LearningLocker/learninglocker#892]
With lots of help, I manged to get LL working on my server.

Windows 2012 r2
IIS
php 5.6

I suspect that it may have something to do with the rewrites. 
I've read many posts of what the .htaccess file should be and none seem to have worked. I have set up the rewrite via my IIS that imports the .htaccess file.  

I can only access LL via the http://learninglocker/public/index.php and am able to login. Once logged in the links Users and LRS do nothing.  Settings and dashboard are the only links that work.

Also, accessing LL via http://learninglocker/public, for some reason redirects me to my home server page, and http://learninglocker provides me with a 403 - Forbidden: Access is denied.

Anyone successful installed this on IIS?

Thanks,
Laura

**Comment by ht2** [comment]
Hi Laura, 

This will be due to not having the Apache `mod_rewrite` extension (which of course you can't have in IIS). This handles rewriting the URLs to all use index.php. For IIS you will need to consult how to do this for Laravel 4.2. This link will help (http://alvarotrigo.com/blog/installing-laravel-4-in-windows-7-with-iis7/) but I will need to close this as it isn't an issue with Learning Locker, rather an issue with your the deployment.
