### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by andrewdisney** [LearningLocker/learninglocker#893]
**Version**
v1.14.0

**Steps to reproduce the bug**
1. Run PHP7

**Expected behaviour**
Application writes and reads learning locker statements

**Actual behaviour**
Application cannot communicate with mongo

**Additional information**
OS: CENT OS 7

I know that there are issues with supporting PHP7 but I wanted to share my team's experience. The first thing we did was change composer.json to include a helpful mongo library for running older php applications with newer mongo adapater.

`"alcaeus/mongo-php-adapter": "^1.0"`

This allowed for perfect reading of mongo data from learning locker in every spot in the application: APIs, reports, and dashboards.

We then had a problem with writing data to mongo. This is because of the version of jenssegers/mongodb learning locker is using. They fixed the issue in 3.0 but 3.0 of jenssegers/mongodb requires a newer version of larvel.

So we found a hot fix for the issue. In the Jenssegers\Mongodb\Collection class we modified the line:
` $result = call_user_func_array(array($this->collection, $method), $parameters); `

To:
```
// based on https://github.com/alcaeus/mongo-php-adapter/issues/107#issuecomment-219393254
if (PHP_VERSION_ID > 70000 && in_array($method, array('insert', 'batchInsert', 'save'))) {
    $saveData = array_shift($parameters);
    $saveParams = array_shift($parameters);
    if (NULL==$saveParams) {
        $saveParams = array();
    }
    $result = call_user_func_array(array($this->collection, $method), array(&$saveData, $saveParams));
} else {
    $result = call_user_func_array(array($this->collection, $method), $parameters);
}
```

This is not an ideal solution but it is a working one for us. Other applications in our environment are going to require PHP7 soon so we are getting all of our applications ready.

The ideal solution would be to upgrade the version of larvel and jenssegers/mongodb that learning locker is using. Has there been an investigation about how much work that would require? Is this something we could help contribute to?

Looking forward to your thoughts.

**Comment by ryansmith94** [comment]
You may want to look into https://github.com/LearningLocker/learninglocker/issues/835

**Comment by rhclayto** [comment]
PHP7's performance is so much better. Making Learning Locker compatible ought to be a high priority.

**Comment by ryansmith94** [comment]
@rhclayto this issue has a low priority for the Learning Locker team here at HT2Labs because we are working on Learning Locker version 2, which has been written in JavaScript to run on NodeJS. Performance of the LRS is a high priority for us and our experimentation has shown that NodeJS will perform better than PHP7 for Learning Locker. I hope that clarifies why this is a low priority.

As always the community is welcome to make contributions to improve version 1 here and we hope to release version 2 open source at some point this year.

**Comment by rhclayto** [comment]
That makes a lot of sense. A persistent running daemon process with an event-loop like Node.js will handle a lot more requests per second than an application that bootstraps for every request, with lower latencies, etc. 👍 on the rewrite. Although it's probably too experimental for you, especially since you are already embarked on a version 2 based on Node.js, but the php-pm project has made some interesting strides in running PHP processes as daemons based on ReactPHP's event-loop, with adapters for Laravel. I myself made a Frankenstein's monster out of a fusion of ReactPHP & Drupal 7 using a similar idea. It works great!

**Comment by ryansmith94** [comment]
For sure, for our hosted installations of version 1 we have somethings in place that reduce the amount of bootstrapping for every request. PHP-PM looks interesting, we use something similar to run NodeJS processes as daemons.

**Comment by rhclayto** [comment]
@andrewdisney Using PHP7, when I try to register a user with the stock Jenssegers\Mongodb\Collection, I get the error `Parameter 1 to MongoCollection::insert() expected to be a reference, value given `. However, when I make the change you suggest, I get `Undefined index: _id`. From the discussion over at https://github.com/alcaeus/mongo-php-adapter/issues/107, it seems that you can have one or the other (by-reference & message signature compatibility, or by-value & _id), but not both. How did you manage to get this working? Is there anything else that needs to be done?

**Comment by rhclayto** [comment]
Well I guess this is just a report from an experimenter in trying to get LearningLocker working on PHP7. Result: unsuccessful, unfortunately. Just kept running into errors trying to do all sorts of things in the user interface.

Trying to create or edit an LRS:

``` Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)

Cannot pass parameter 1 by reference 
```

Trying to look at Statements: 

``` MongoConnectionException (2)

error processing query: ns=lrs.statementsTree: $and active == true lrs_id == ObjectId('58d0019fc3a6a24d572b33c4') voided == false Sort: {} Proj: {} planner returned error: bad hint 
```

And so on. I think I will try again when version 2 is out.

**Comment by ht2** [comment]
The bad hint is due to you not having all the indexes in the most recent migration: https://github.com/LearningLocker/learninglocker/blob/develop/app/database/migrations/2016_05_20_130927_create_statement_indexes.php#L26

As to your reference issue, you'd have to look at modifying where the jenseggers class calls on the `batchInsert` method. You can see it here, in the forked version of jenseggers/mongodb that we use for LL (it allows us to hint on counts etc): https://github.com/LearningLocker/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Query/Builder.php#L463

**Comment by rhclayto** [comment]
When doing php artisan migrate upon initial installation, I got the following error:

```
Status: 500 Error: Index with name: statement.id_1_lrs_id_1 already exists with different options

  [MongoResultException]
  Index with name: statement.id_1_lrs_id_1 already exists with different options



  [MongoDB\Driver\Exception\RuntimeException]
  Index with name: statement.id_1_lrs_id_1 already exists with different options
```

Related to this, I suppose?

**Comment by ht2** [comment]
Sounds like you've fallen out of sync with the migrations.

Go to your mongo CLI and run this:
`db.statements.createIndex({lrs_id: 1, active: -1, voided: 1}, {background:true})`

You can run similar on any other index in that migration you don't have ('db.statements.getIndexes()`). The background:true means its non-blocking and will build in the background.

**Comment by rhclayto** [comment]
Thank you, indeed that solved the issue with viewing the Statements page.

**Comment by pix-art** [comment]
What is the status on this one? Are you guys planning on making this a priority?

**Comment by ryansmith94** [comment]
Hey @pix-art [my earlier comment](https://github.com/LearningLocker/learninglocker/issues/893#issuecomment-287719617) describes why this is a low priority.

> We are working on Learning Locker version 2, which has been written in JavaScript to run on NodeJS. Performance of the LRS is a high priority for us and our experimentation has shown that NodeJS will perform better than PHP7 for Learning Locker.

> As always the community is welcome to make contributions to improve version 1 here and we hope to release version 2 open source at some point this year.

**Comment by ht2** [comment]
I'm going to close this issue as the project is now release with Node for v2.0.0. We are happy to accept any contributions that advance v1 for PHP 7 however.
