### ISSUE TITLE
Insert statement - curl

### ISSUE THREAD

**Issue by rena7o8** [LearningLocker/learninglocker#923]
I am using the following code to insert client's in my lrs:

![image](https://cloud.githubusercontent.com/assets/26470305/25177178/db7a9ec8-24f8-11e7-9914-26a0484aa9ca.png)

What I should change to insert statements?

**Comment by ryansmith94** [comment]
Hey @rena7o8, you can see what needs to be changed by checking out [our Postman collections](http://docs.learninglocker.net/postman/) and the [xAPI specification](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md).

**Comment by rena7o8** [comment]
Hi again @ryansmith94 , I checked the Postman collections, and I think you are talking about this: https://www.getpostman.com/collections/7a3452d868013026fef6

It's not helping that much. What's that mean?

I already have a proper json file created in php (my statement) and I still trying to insert it with same method as showed above. I think the problem it's the "CURLOPT_URL" option, it should be a different endpoint link.

**Comment by ryansmith94** [comment]
Did you look at the [other link for the spec](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#stmtres)?

**Comment by rena7o8** [comment]
Ok, I take a lock and I think the endpoint should be : http://example.com/xAPI/statements

I changed it but now I get this error:
![image](https://cloud.githubusercontent.com/assets/26470305/25192025/8a8d4868-2529-11e7-8a11-168358ce8bf8.png)

The array above, it's just an echo of my statement.

**Comment by ht2** [comment]
Hi @rena7o8 - I'm sorry but this is issues board is for technical issues related to the Learning Locker software, not how to implement the xAPI. I think you need to read up on the spec document that @ryansmith94 linked to above. That, together with the xAPI endpoint available in your clients page has everything you need to know about using the xAPI.

Given you are having issues at the first hurdle, I would also strongly suggest using a library to send statements such as https://github.com/RusticiSoftware/TinCanPHP rather than trying to implement it yourself.
